import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
// import fo from '@/shared/fonts/a_citynova_bold.ttf'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const citynova = localFont({
  src: '../shared/fonts/a_citynova_bold.ttf',
  display: 'block',
  variable: '--font-citynova',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${citynova.variable}`}>
      <body>{children}</body>
    </html>
  );
}
